version: "3.8"

services:
  flight_price_api:
    build: .
    container_name: flight_price_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: [ "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000" ]

  flight_price_frontend:
    build: .
    container_name: flight_price_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: [ "streamlit", "run", "app_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0" ]
    depends_on:
      - flight_price_api
